export interface Course {
  id: string;
  title: string;
  slug: string;
  shortDescription: string;
  description: string;
  price: number;
  originalPrice?: number;
  duration: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  category: string;
  thumbnail: string;
  rating: number;
  studentsEnrolled: number;
  instructorName: string;
  instructorRole: string;
  isFeatured: boolean;
  isNew?: boolean;
  batchStartingSoon?: boolean;
  syllabus: { module: string; topics: string[] }[];
  learningOutcomes: string[];
  tools: string[];
}

export const courses: Course[] = [
  {
    id: '1',
    title: 'AI Tools Mastery for Beginners',
    slug: 'ai-tools-mastery-beginners',
    shortDescription: 'Master ChatGPT, Claude, Canva AI, and 10+ AI tools to 10x your productivity.',
    description: 'A comprehensive hands-on program that takes you from AI-curious to AI-proficient. Learn to use the most powerful AI tools in the market through real-world projects. No coding required.',
    price: 4999,
    originalPrice: 9999,
    duration: '4 Weeks',
    level: 'Beginner',
    category: 'AI Tools',
    thumbnail: '/images/course-ai-tools.jpg',
    rating: 4.8,
    studentsEnrolled: 234,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: true,
    syllabus: [
      { module: 'Introduction to AI', topics: ['What is AI?', 'AI vs ML vs DL', 'AI in daily life', 'Setting up accounts'] },
      { module: 'ChatGPT & Claude Mastery', topics: ['Prompt engineering', 'Advanced prompts', 'Content creation', 'Research & analysis'] },
      { module: 'Visual AI Tools', topics: ['Canva AI', 'Midjourney basics', 'HeyGen for videos', 'AI image editing'] },
      { module: 'AI for Business', topics: ['AI automation', 'Email & marketing AI', 'AI for social media', 'Building AI workflows'] },
    ],
    learningOutcomes: [
      'Use 10+ AI tools confidently for work and personal projects',
      'Write effective prompts that get the best AI outputs',
      'Create professional content using AI in minutes',
      'Automate repetitive tasks using AI workflows',
      'Build a portfolio of AI-powered projects',
    ],
    tools: ['ChatGPT', 'Claude', 'Canva AI', 'Midjourney', 'HeyGen', 'Notion AI', 'Gamma', 'Perplexity'],
  },
  {
    id: '2',
    title: 'AI for Digital Marketing',
    slug: 'ai-digital-marketing',
    shortDescription: 'Learn to create campaigns, content, ads, and funnels using AI — and start earning within 30 days of graduation.',
    description: 'A 12-week hands-on certification program that takes you from complete beginner to working digital marketer. Master AI-powered content creation, Meta advertising, WhatsApp marketing, and client acquisition — built specifically for freelancers and small agency owners in Punjab and beyond. You\'ll pick a real local business on Day 1 and spend 12 weeks building everything for them: brand identity, content, videos, ads, landing pages, funnels, and client reports. By Week 12, you walk out with a portfolio, paying clients, and a clear income roadmap.',
    price: 24999,
    originalPrice: 34999,
    duration: '12 Weeks',
    level: 'Beginner' as const,
    category: 'Marketing',
    thumbnail: '/images/course-marketing.jpg',
    rating: 4.9,
    studentsEnrolled: 156,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: true,
    syllabus: [
      {
        module: 'Phase 1: Foundations (Weeks 1–3)',
        topics: [
          'Week 1 — AI Fundamentals + The Marketing Opportunity: How LLMs work, ChatGPT vs Claude vs Gemini, marketing industry overview, career paths, AI ethics',
          'Week 2 — Digital Marketing Fundamentals + Niche Selection: Marketing funnel, channels overview, local business needs, pick your real business case study, buddy system begins',
          'Week 3 — Prompt Engineering for Marketers: Prompt frameworks (Role + Context + Task + Format + Tone), multilingual prompting (Punjabi/Hindi/English), AI workflow system, prompt chaining, 20-task Prompt Challenge',
        ],
      },
      {
        module: 'Phase 2: Content & Creative (Weeks 4–6)',
        topics: [
          'Week 4 — AI-Powered Copywriting: Captions, blogs, product descriptions, email sequences, content pillars, 30-day content calendar creation, repurposing one idea into 5 formats',
          'Week 5 — AI for Visual Design: Brand identity (logo, colors, fonts), social media creatives, reusable templates, Canva Pro, Microsoft Designer, Adobe Firefly — build brand kit + 15 creatives',
          'Week 6 — AI for Video Content: Short-form video (Reels, Shorts, WhatsApp status), AI editing with CapCut, AI voiceovers with ElevenLabs, batch creation — create 5 videos including Punjabi/Hindi',
        ],
      },
      {
        module: 'Phase 3: Growth & Advertising (Weeks 7–9)',
        topics: [
          'Week 7 — Local Marketing: Google My Business setup & optimization, local SEO, WhatsApp Business deep dive (catalog, auto-replies, broadcasts, funnels), Google Analytics & Search Console basics',
          'Week 8 — Meta Ads Deep Dive Part 1: How Meta advertising works, ad objectives, local audience targeting, ad formats (image, video, carousel, stories, reels), AI-powered ad copy, budget planning',
          'Week 9 — Meta Ads Part 2 + Landing Pages + Funnels: A/B testing, retargeting, lookalike audiences, landing page creation (Systeme.io/Framer), complete funnel build, LIVE AD with ₹200–500 real budget',
        ],
      },
      {
        module: 'Phase 4: Business Building & Certification (Weeks 10–12)',
        topics: [
          'Week 10 — Automation, CRM & Reporting: Email marketing (Mailchimp), social scheduling, CRM setup (Zoho/HubSpot), workflow automation (Make.com/Zapier), client reporting, invoicing',
          'Week 11 — Client Acquisition & Business Launch: Service packaging (₹5K, ₹10K, ₹25K/month packages), rate card creation, client outreach (WhatsApp, Instagram DMs, walk-in pitches), portfolio website, Fiverr/Upwork/LinkedIn setup',
          'Week 12 — Certification & Graduation: Final presentation (15–20 min, 100-point rubric), income roadmap, 30-60-90 day action plan, Resource Vault handover (50+ templates), certification ceremony, alumni WhatsApp group',
        ],
      },
    ],
    learningOutcomes: [
      'Build complete marketing campaigns for real businesses from scratch',
      'Run live Meta ad campaigns with real budget and analyze results',
      'Create professional content — posts, reels, videos — in Punjabi, Hindi, and English using AI',
      'Set up Google My Business, WhatsApp Business, and local SEO for any business',
      'Build landing pages and marketing funnels that convert leads into customers',
      'Package and sell your services at ₹5K, ₹10K, and ₹25K/month to local businesses',
      'Set up CRM, email automation, and professional client reporting workflows',
      'Launch your freelance career with a portfolio, rate card, and ready-to-send proposals',
    ],
    tools: ['ChatGPT', 'Claude', 'Gemini', 'Canva', 'CapCut', 'ElevenLabs', 'Meta Ads Manager', 'Google Business Profile', 'WhatsApp Business', 'Google Analytics', 'Ubersuggest', 'Mailchimp', 'Zoho CRM', 'Make.com', 'Systeme.io'],
  },
  {
    id: '3',
    title: 'AI Explorer for School Kids — Junior',
    slug: 'ai-explorer-school-kids-junior',
    shortDescription: 'A fun, hands-on AI course for Class 5–7 students. Learn to use ChatGPT, Canva AI, and 10+ tools for school projects, creative storytelling, art, and everyday problem-solving.',
    description: 'A fun, hands-on AI course for Class 5–7 students. Learn to use ChatGPT, Canva AI, and 10+ tools for school projects, creative storytelling, art, and everyday problem-solving.',
    price: 2999,
    originalPrice: 4999,
    duration: '4 Weeks',
    level: 'Beginner',
    category: 'AI Tools',
    thumbnail: '/images/course-school-junior.jpg',
    rating: 0,
    studentsEnrolled: 0,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: true,
    isNew: true,
    batchStartingSoon: true,
    syllabus: [
      { module: 'Introduction to AI', topics: ['What is AI?', 'How AI thinks', 'AI in everyday life', 'Staying safe online with AI'] },
      { module: 'ChatGPT for School', topics: ['Asking smart questions', 'AI for homework help', 'Storytelling with AI', 'Creative writing projects'] },
      { module: 'Visual & Creative AI', topics: ['Canva AI for projects', 'AI art creation', 'Making presentations', 'Designing posters with AI'] },
      { module: 'AI Problem Solving', topics: ['Using AI to solve real problems', 'Science projects with AI', 'AI quiz games', 'Showcase your AI project'] },
    ],
    learningOutcomes: [
      'Use ChatGPT and Canva AI for school projects',
      'Create AI-powered stories, art, and presentations',
      'Understand how AI works in simple, fun ways',
      'Solve everyday problems using AI tools',
      'Build confidence with technology from an early age',
    ],
    tools: ['ChatGPT', 'Canva AI', 'Google Gemini', 'Bing Image Creator', 'Gamma', 'Padlet'],
  },
  {
    id: '3b',
    title: 'AI Explorer for School Kids — Senior',
    slug: 'ai-explorer-school-kids-senior',
    shortDescription: 'A future-ready AI course for Class 8–10 students. Master prompt engineering, use AI for board exam prep, build your first chatbot, and create professional content — all in 4 weeks.',
    description: 'A future-ready AI course for Class 8–10 students. Master prompt engineering, use AI for board exam prep, build your first chatbot, and create professional content — all in 4 weeks.',
    price: 3999,
    originalPrice: 5999,
    duration: '4 Weeks',
    level: 'Intermediate',
    category: 'AI Tools',
    thumbnail: '/images/course-school-senior.jpg',
    rating: 0,
    studentsEnrolled: 0,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: true,
    isNew: true,
    batchStartingSoon: true,
    syllabus: [
      { module: 'AI & Prompt Engineering', topics: ['How LLMs work', 'Writing effective prompts', 'Prompt frameworks', 'AI vs human thinking'] },
      { module: 'AI for Board Exam Prep', topics: ['Study plans with AI', 'AI for note summarisation', 'Practice Q&A with AI', 'Revision using flashcards'] },
      { module: 'Build Your First Chatbot', topics: ['Custom GPT creation', 'Training your chatbot', 'Real-world chatbot use cases', 'Sharing your bot'] },
      { module: 'Content & Career with AI', topics: ['LinkedIn & resume with AI', 'AI video creation', 'AI for projects & reports', 'Future careers in AI'] },
    ],
    learningOutcomes: [
      'Write advanced prompts that get professional-quality outputs',
      'Use AI to ace board exam preparation',
      'Build and deploy your own custom chatbot',
      'Create professional content — videos, posts, and reports — with AI',
      'Understand career opportunities in the AI era',
    ],
    tools: ['ChatGPT', 'Claude', 'Canva AI', 'HeyGen', 'Gamma', 'Notion AI', 'Custom GPT Builder'],
  },
  {
    id: '4',
    title: 'AI for Business Leaders',
    slug: 'ai-business-leaders',
    shortDescription: 'Strategic AI adoption for entrepreneurs and managers. No coding required.',
    description: 'Designed for business owners and managers who need to understand AI strategically. Learn how to identify AI opportunities, evaluate tools, manage AI projects, and lead AI transformation in your organization.',
    price: 9999,
    originalPrice: 19999,
    duration: '4 Weeks',
    level: 'Intermediate',
    category: 'Business',
    thumbnail: '/images/course-business.jpg',
    rating: 4.8,
    studentsEnrolled: 87,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: false,
    syllabus: [
      { module: 'AI Strategy', topics: ['AI landscape overview', 'Identifying AI opportunities', 'ROI of AI adoption', 'AI readiness assessment'] },
      { module: 'AI for Operations', topics: ['Process automation', 'AI in HR & recruitment', 'Customer service AI', 'Supply chain AI'] },
      { module: 'AI Implementation', topics: ['Evaluating AI vendors', 'Managing AI projects', 'Data strategy', 'Change management'] },
      { module: 'Future of AI', topics: ['Emerging AI trends', 'AI ethics & governance', 'Building AI-first culture', 'Case studies'] },
    ],
    learningOutcomes: [
      'Develop an AI strategy for your organization',
      'Evaluate and select the right AI tools for business needs',
      'Lead AI implementation projects effectively',
      'Make data-driven decisions about AI investments',
    ],
    tools: ['ChatGPT', 'Claude', 'Zapier AI', 'Power Automate', 'Notion AI', 'Otter.ai'],
  },
  {
    id: '5',
    title: 'Generative AI & Prompt Engineering',
    slug: 'generative-ai-prompt-engineering',
    shortDescription: 'Master the art of communicating with AI. Advanced prompt techniques for professionals.',
    description: 'Deep dive into generative AI models and advanced prompt engineering. Learn to get consistently excellent results from ChatGPT, Claude, Midjourney, and other generative AI tools through systematic prompt design.',
    price: 5999,
    originalPrice: 11999,
    duration: '3 Weeks',
    level: 'Advanced',
    category: 'AI Tools',
    thumbnail: '/images/course-prompts.jpg',
    rating: 4.9,
    studentsEnrolled: 312,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: true,
    syllabus: [
      { module: 'How LLMs Work', topics: ['Transformer architecture simplified', 'Tokens & context windows', 'Temperature & parameters', 'Model comparison'] },
      { module: 'Prompt Frameworks', topics: ['CRISP framework', 'Chain-of-thought', 'Few-shot prompting', 'System prompts'] },
      { module: 'Advanced Techniques', topics: ['Role-based prompting', 'Multi-step workflows', 'Prompt chaining', 'Custom GPTs & Claude Projects'] },
      { module: 'Real-World Applications', topics: ['Content production pipeline', 'Code generation', 'Data analysis prompts', 'Creative AI workflows'] },
    ],
    learningOutcomes: [
      'Understand how large language models work under the hood',
      'Design prompts that consistently produce high-quality outputs',
      'Build multi-step AI workflows for complex tasks',
      'Create custom AI assistants for specific use cases',
    ],
    tools: ['ChatGPT', 'Claude', 'Gemini', 'Midjourney', 'DALL-E', 'Stable Diffusion'],
  },
  {
    id: '6',
    title: 'AI Video & Content Creation',
    slug: 'ai-video-content-creation',
    shortDescription: 'Create professional videos, graphics, and content at scale using AI tools.',
    description: 'Learn to produce studio-quality videos, graphics, presentations, and written content using the latest AI tools. Perfect for content creators, marketers, and entrepreneurs who want to scale their content production.',
    price: 6999,
    originalPrice: 12999,
    duration: '5 Weeks',
    level: 'Beginner',
    category: 'Content Creation',
    thumbnail: '/images/course-content.jpg',
    rating: 4.7,
    studentsEnrolled: 189,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: false,
    syllabus: [
      { module: 'AI Writing Tools', topics: ['Long-form content', 'Social media copy', 'Email marketing', 'Blog writing with AI'] },
      { module: 'AI Video Production', topics: ['HeyGen avatars', 'Runway ML editing', 'AI voiceovers', 'Automated video creation'] },
      { module: 'AI Graphics & Design', topics: ['Canva AI features', 'AI image generation', 'Brand kit automation', 'Presentation AI'] },
      { module: 'Content at Scale', topics: ['Content calendars with AI', 'Repurposing workflows', 'Multi-platform publishing', 'Analytics & optimization'] },
    ],
    learningOutcomes: [
      'Produce professional videos without a camera or studio',
      'Create weeks of social media content in hours',
      'Design graphics and presentations using AI tools',
      'Build a scalable content production workflow',
    ],
    tools: ['HeyGen', 'Runway ML', 'Canva AI', 'Descript', 'ElevenLabs', 'Gamma', 'Opus Clip'],
  },
  {
    id: '7',
    title: 'AI Power — 8-Week Program',
    slug: 'ai-power-8-week-program',
    shortDescription: 'Punjab\'s first practical AI program for non-tech students. Master 15+ AI tools, build 4 portfolio projects, and start freelancing — no coding required.',
    description: 'An 8-week hands-on program designed for students from non-IT backgrounds — BBA, B.Com, BA, IELTS aspirants, and anyone who wants to use AI professionally without writing a single line of code. You\'ll master 15+ AI tools, build real projects for local businesses, create a portfolio website, and set up your freelancing profile — all in 8 weeks. By the end, you\'ll have the skills, the portfolio, and the confidence to earn ₹20,000–50,000/month through AI freelancing.',
    price: 7999,
    originalPrice: 9999,
    duration: '8 Weeks',
    level: 'Beginner',
    category: 'AI Tools',
    thumbnail: '/images/course-ai-power.jpg',
    rating: 0,
    studentsEnrolled: 0,
    instructorName: 'Parveen Sukhija',
    instructorRole: 'Founder, Uplrn AI Labs',
    isFeatured: true,
    isNew: true,
    batchStartingSoon: true,
    syllabus: [
      {
        module: 'Week 1: AI Foundations — "Soch Badlo"',
        topics: [
          'What is AI, ML, ChatGPT — myths vs reality',
          'Live demo: 10 tasks AI can do in 10 minutes that take you 10 hours',
          'Hands-on: Sign up & explore ChatGPT, Gemini, Claude, Perplexity',
          'Prompting 101 — how to talk to AI like a pro',
          'Privacy, hallucinations, what NOT to trust AI with',
          'Deliverable: Write 20 professional prompts for your field',
        ],
      },
      {
        module: 'Week 2: AI for Academics & Research',
        topics: [
          'AI for assignments, essays, summaries, and notes',
          'Research like a PhD student using Perplexity AI + Google Scholar AI',
          'IELTS/PTE prep using AI — writing practice, vocabulary building, mock feedback',
          'Study abroad SOP & LOR drafting with AI assistance',
          'Deliverable: AI-assisted SOP draft or research summary',
        ],
      },
      {
        module: 'Week 3: AI for Content & Social Media',
        topics: [
          'AI writing tools — blogs, captions, scripts, emails (ChatGPT, Claude)',
          'AI image generation — Canva AI, Leonardo AI, Ideogram',
          'AI video — CapCut AI, InVideo AI',
          'Build a personal brand on Instagram/LinkedIn using AI',
          'Deliverable: 1-week content calendar + 5 AI-generated posts ready to publish',
        ],
      },
      {
        module: 'Week 4: AI for Business & Money',
        topics: [
          'AI for local businesses — shops, clinics, tuition centres, restaurants in Punjab',
          'Invoice, billing, inventory ideas using AI + Google Sheets',
          'Customer WhatsApp auto-replies using AI chatbots',
          'Market research & competitor analysis with AI',
          'Case study: How a local Punjab business can use AI to grow',
          'Deliverable: AI business improvement plan for a real local business',
        ],
      },
      {
        module: 'Week 5: No-Code Automation & Workflows',
        topics: [
          'Zapier / Make — connect apps without code',
          'Build automations: Form → WhatsApp notification → Google Sheet → Email',
          'AI + Google Sheets/Excel — formulas, data cleaning, dashboards',
          'Notion AI for project management & personal productivity',
          'Deliverable: Build 3 working automations you can show employers',
        ],
      },
      {
        module: 'Week 6: AI Agents & Chatbots (Zero Code)',
        topics: [
          'What are AI agents — the future of work',
          'Build a customer support chatbot (Botpress / Voiceflow)',
          'Build a personal AI assistant using custom GPTs',
          'AI voice bots — basics of conversational AI',
          'Deliverable: Working chatbot for a real use case (education, business, or personal)',
        ],
      },
      {
        module: 'Week 7: AI for Career & Freelancing',
        topics: [
          'AI-optimized resume & cover letter building',
          'LinkedIn profile makeover using AI',
          'Freelancing with AI — Fiverr/Upwork gigs: content writing, social media management, chatbot building, presentations, data research',
          'How to price your services & land your first client',
          'Deliverable: Live freelancing profile + 3 portfolio samples',
        ],
      },
      {
        module: 'Week 8: Capstone + Demo Day',
        topics: [
          'Choose your capstone: AI solution for a local business, AI-powered personal brand, AI chatbot for an institution, or AI content agency starter kit',
          'Portfolio website building using AI + free tools',
          'Demo Day — present to local business owners, parents & team',
          'Certificate ceremony',
          'Deliverable: Complete portfolio website + capstone project + certificate',
        ],
      },
    ],
    learningOutcomes: [
      'Use 15+ AI tools confidently for work, academics, and freelancing',
      'Write professional prompts that get high-quality AI outputs every time',
      'Create content — posts, reels, videos, blogs — using AI in Punjabi, Hindi, and English',
      'Build AI-powered automation workflows without writing any code',
      'Create chatbots and AI assistants for real business use cases',
      'Build a professional portfolio website showcasing 4 real projects',
      'Set up freelancing profiles on Fiverr, Upwork, and LinkedIn — ready to earn',
      'Develop an AI business improvement plan for real local businesses',
    ],
    tools: ['ChatGPT', 'Claude', 'Gemini', 'Perplexity', 'Canva AI', 'Leonardo AI', 'CapCut AI', 'InVideo AI', 'Gamma AI', 'Zapier', 'Make', 'Notion AI', 'Botpress', 'Custom GPTs', 'Grammarly AI'],
  },
];

export const categories = [...new Set(courses.map(c => c.category))];
